export const AVAILABILITY_LIST_REQUEST = 'AVAILABILITY_LIST_REQUEST';
export const AVAILABILITY_LIST_SUCCESS = 'AVAILABILITY_LIST_SUCCESS';
export const AVAILABILITY_LIST_FAIL = 'AVAILABILITY_LIST_FAIL';
export const AVAILABILITY_LIST_RESET = 'AVAILABILITY_LIST_RESET';

export const AVAILABILITY_CREATE_REQUEST = 'AVAILABILITY_CREATE_REQUEST';
export const AVAILABILITY_CREATE_SUCCESS = 'AVAILABILITY_CREATE_SUCCESS';
export const AVAILABILITY_CREATE_FAIL = 'AVAILABILITY_CREATE_FAIL';

export const AVAILABILITY_DETAILS_REQUEST = 'AVAILABILITY_DETAILS_REQUEST';
export const AVAILABILITY_DETAILS_SUCCESS = 'AVAILABILITY_DETAILS_SUCCESS';
export const AVAILABILITY_DETAILS_FAIL = 'AVAILABILITY_DETAILS_FAIL';

export const AVAILABILITY_DELETE_REQUEST = 'AVAILABILITY_DELETE_REQUEST';
export const AVAILABILITY_DELETE_SUCCESS = 'AVAILABILITY_DELETE_SUCCESS';
export const AVAILABILITY_DELETE_FAIL = 'AVAILABILITY_DELETE_FAIL';

export const AVAILABILITY_UPDATE_REQUEST = 'AVAILABILITY_UPDATE_REQUEST';
export const AVAILABILITY_UPDATE_SUCCESS = 'AVAILABILITY_UPDATE_SUCCESS';
export const AVAILABILITY_UPDATE_FAIL = 'AVAILABILITYPRODUCT_UPDATE_FAIL';
export const AVAILABILITY_UPDATE_RESET = 'AVAILABILITY_UPDATE_RESET';
